src/Entity/Addons.php
<?php

namespace App\Entity;

use App\Entity\AddonsType;
use App\Repository\AddonsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AddonsRepository::class)]
class Addons
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'addons')]
    #[Assert\NotBlank]
    private ?AddonsType $addOnType = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $addOnTitle = null;

    #[ORM\Column(length: 2500, nullable: true)]
    #[Assert\NotBlank]
    private ?string $addOnTypeJson = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank]
    private ?int $time = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    private ?string $monthDay = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $Price = null;

    #[ORM\Column(type: Types::SMALLINT)]
    #[Assert\NotBlank]
    private ?int $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $createdAt = null;    

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'addonsId', targetEntity: CaSubscriptionAddons::class)]
    private Collection $caSubscriptionAddons;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->caSubscriptionAddons = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddOnType(): ?AddonsType
    {
        return $this->addOnType;
    }

    public function setAddOnType(?AddonsType $addOnType): self
    {
        $this->addOnType = $addOnType;

        return $this;
    }

    public function getAddOnTitle(): ?string
    {
        return $this->addOnTitle;
    }

    public function setAddOnTitle(string $addOnTitle): self
    {
        $this->addOnTitle = $addOnTitle;

        return $this;
    }

    public function getAddOnTypeJson(): ?string
    {
        return $this->addOnTypeJson;
    }

    public function setAddOnTypeJson(?string $addOnTypeJson): self
    {
        $this->addOnTypeJson = $addOnTypeJson;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(?int $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getMonthDay(): ?string
    {
        return $this->monthDay;
    }

    public function setMonthDay(?string $monthDay): self
    {
        $this->monthDay = $monthDay;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }    

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, CaSubscriptionAddons>
     */
    public function getCaSubscriptionAddons(): Collection
    {
        return $this->caSubscriptionAddons;
    }

    public function addCaSubscriptionAddon(CaSubscriptionAddons $caSubscriptionAddon): self
    {
        if (!$this->caSubscriptionAddons->contains($caSubscriptionAddon)) {
            $this->caSubscriptionAddons->add($caSubscriptionAddon);
            $caSubscriptionAddon->setAddonsId($this);
        }

        return $this;
    }

    public function removeCaSubscriptionAddon(CaSubscriptionAddons $caSubscriptionAddon): self
    {
        if ($this->caSubscriptionAddons->removeElement($caSubscriptionAddon)) {
            // set the owning side to null (unless already changed)
            if ($caSubscriptionAddon->getAddonsId() === $this) {
                $caSubscriptionAddon->setAddonsId(null);
            }
        }

        return $this;
    }
}

src/Controller/SubscriptionsController.php
<?php

namespace App\Controller;

use App\Entity\Subscriptions;
use App\Form\SubscriptionFormType;
use App\Repository\SubscriptionsRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class SubscriptionsController extends AbstractController
{
    private $subscriptionsRepository;

    public function __construct(SubscriptionsRepository $subscriptionsRepository)
    {
        $this->subscriptionsRepository = $subscriptionsRepository;
    }

    #[Route('/subscriptions', name: 'app_subscriptions')]
    public function index(Request $request): Response
    {   
        $searchBy = $request->query->get('searchBy', null);         
        $sortBy = $request->query->get('sortby', null);        
        if($sortBy == '')
        {
            $sortByFeild = 's.createdAt'; 
            $order = 'DESC';             
        }
        else
        {
            $sortbyexpd = explode('-',$sortBy);  
            $sortByFeild = $sortbyexpd[0];
            $order = $sortbyexpd[1];
        }

        $page = intval($request->query->get('page', 1));
        $limit = intval($request->query->get('limit', 5));
        $start_from = ($limit * ($page-1))+1;    

        $queryBuilder = $this->subscriptionsRepository->createPaginatedQueryBuilder($sortByFeild,$order,$searchBy);
        $adapter = new QueryAdapter($queryBuilder);
        $subscriptions = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $page,
            $limit
        );
           
        return $this->render('subscriptions/index.html.twig', [
            'subscriptions' => $subscriptions,
            'limit' => intval($request->query->get('limit', 5)),
            'sortby' => $sortByFeild,
            'order' => $order,
            'searchBy' => $searchBy,
            'start_from' => $start_from
        ]);
    }
    #[Route('/subscriptions/create', name: 'create_subscriptions')]
    public function create(Request $request, ValidatorInterface $validator): Response
    {
        $subscription  = new Subscriptions();
        $form = $this->createForm(SubscriptionFormType::class,$subscription, ['attr' => ['class' => 'needs-validation','novalidate'=>'']]);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {            
            $this->subscriptionsRepository->save($subscription,true);            
            $this->addFlash('success', 'Subscription Created!');
            return $this->redirectToRoute('app_subscriptions');
        }

        return $this->render('subscriptions/create.html.twig',[
            'form' => $form->createView()
        ]);
    }
    #[Route('/subscriptions/edit/{id}', name: 'edit_subscription')]
    public function update($id, Request $request) : Response 
    {
         $subscription = $this->subscriptionsRepository->find($id);

         $form = $this->createForm(SubscriptionFormType::class, $subscription, ['attr' => ['class' => 'needs-validation','novalidate'=>'']]);
         $form->handleRequest($request);
         if ($form->isSubmitted() && $form->isValid()) {            
            $this->subscriptionsRepository->save($subscription,true);            
            $this->addFlash('success', 'Subscription Updated!');
            return $this->redirectToRoute('app_subscriptions');
         }
         return $this->render('subscriptions/edit.html.twig', [
             'subscription' => $subscription,
             'form' => $form->createView()
         ]);
    }
    #[Route('/subscriptions/delete/{id}', name: 'delete_subscription')]
    public function delete($id): Response
    {        
        $subscription = $this->subscriptionsRepository->find($id);
        $this->subscriptionsRepository->remove($subscription,true);        

        $this->addFlash('success', 'Subscription Deleted!');
        return $this->redirectToRoute('app_subscriptions');
    }
}

templates/subscriptions/create.html.twig
{% extends 'layouts/layout.html.twig' %}

{% block title %}Dashboard | Superadmin!{% endblock %}

{% block content %}
  <!-- start: basic forms -->
        <div class="card mb-3">
          <div class="card-header position-relative d-flex" style="min-height:90px;">
            <div class="d-flex align-items-center w-100">
              <div class="me-auto">
                <h5 class="my-2 text-white position-relative z-index-1">Add Subscription</h5>
              </div>

            </div>
            <div class="bg-holder rounded-3 rounded-bottom-0" style="background-image:url(/assets/img/generic/4.jpg);"></div>
          </div>
          <div class="card-body bg-light">
            {{ form_start(form) }}
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Subscription Plan Name</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.planTitle)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.planTitle, {'attr': {'class': 'form-control mb-3'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.planTitle) }}
                 </div>
                </div>
                
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Validity</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">                  
                  <div class="row">
                    <div class="col {% if form_errors(form.time)|length > 0 %} div-form-error{% endif %}">
                      {{ form_widget(form.time, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}                      
                    </div>
                    <div class="col-auto">
                      <div class="mb-3" style="min-width:130px;">
                       {{ form_widget(form.monthDay, {'attr': {'class': 'form-select form-select-sm'}}) }}
                      </div>
                    </div>
                    <div class="form-error">
                          {{ form_errors(form.time) }}
                      </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Storage Space</label>
                </div>

                

                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.storageSize)|length > 0 %} div-form-error{% endif %}">
                  <div class="input-group mb-3">
                    {{ form_widget(form.storageSize, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">GB</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.storageSize) }}
                  </div>
                </div>    
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Clients</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfClients)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfClients, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfClients) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Employees</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfEmployee)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfEmployee, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfEmployee) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Users</label>
                </div>
                <div class="col-12 col-sm-6 col-md-5 ">
                  <div class="input-group mb-3 {% if form_errors(form.CAEmployeeAndOwnerLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.CAEmployeeAndOwnerLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">CA Employee & OwnerLogin</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.CAEmployeeAndOwnerLogin) }}
                  </div>
                  <div class="input-group mb-3 {% if form_errors(form.ClientOwnerAndEmployeeLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.ClientOwnerAndEmployeeLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">ClientOwner & Employee Login</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.ClientOwnerAndEmployeeLogin) }}
                  </div>
                  <div class="input-group mb-3 {% if form_errors(form.ClientVendorLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.ClientVendorLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">Client Vendor Login</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.ClientVendorLogin) }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Transactions</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfTransaction)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfTransaction, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfTransaction) }}
                 </div>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Features</label>
                </div>
                <div class="col">
                  <div class="py-2 mb-2">
                    <div class="row">
                      <div class="col-12">
                        <div class="form-check form-switch mb-0">                          
                          {{ form_widget(form.taskManager, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_1">Task Manager</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.fileManager, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_2">File Manager</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.eCommerce, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_4">E-Commerce</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.templateCustomization, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_5">Tamplate - Customization for import</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.liveReportClientMobileApp, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_6">Live reports on client mobile app</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.clientLoginApp, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_6">Client Login Mobile App</label>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Price</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.price)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.price, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.price) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Status</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                  {{ form_widget(form.status, {'attr': {'class': 'form-select form-select-sm mb-3'}}) }}
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Display on Portal</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                  <div class="form-check form-switch">
                    {{ form_widget(form.displayOnPortal, {'attr': {'class': 'form-check-input'}}) }}
                    <label class="form-check-label" for="dp_radio_7">Yes</label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12 my-2 text-end">
                  <button type="submit" class="btn btn-primary">Add Plan</button>
                </div>
              </div>
            {{ form_end(form) }}

          </div>
        </div>
{% endblock %}

templates/subscriptions/edit.html.twig
{% extends 'layouts/layout.html.twig' %}

{% block title %}Dashboard | Superadmin!{% endblock %}

{% block content %}
  <!-- start: basic forms -->
        <div class="card mb-3 page-main-content">
          <div class="card-header position-relative d-flex" style="min-height:90px;">
            <div class="d-flex align-items-center w-100">
              <div class="me-auto">
                <h5 class="my-2 text-white position-relative z-index-1">Edit Subscription</h5>
              </div>

            </div>
            <div class="bg-holder rounded-3 rounded-bottom-0" style="background-image:url(/assets/img/generic/4.jpg);"></div>
          </div>
          <div class="card-body bg-light">
            {{ form_start(form) }}
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Subscription Plan Name</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.planTitle)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.planTitle, {'attr': {'class': 'form-control mb-3'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.planTitle) }}
                 </div>
                </div>
                
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Validity</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">                  
                  <div class="row">
                    <div class="col {% if form_errors(form.time)|length > 0 %} div-form-error{% endif %}">
                      {{ form_widget(form.time, {'attr': {'class': 'form-control mb-3'}}) }}                      
                    </div>
                    <div class="col-auto">
                      <div class="mb-3" style="min-width:130px;">
                       {{ form_widget(form.monthDay, {'attr': {'class': 'form-select form-select-sm'}}) }}
                      </div>
                    </div>
                    <div class="form-error">
                          {{ form_errors(form.time) }}
                      </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Storage Space</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.storageSize)|length > 0 %} div-form-error{% endif %}">
                  <div class="input-group mb-3">
                  {{ form_widget(form.storageSize, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                  <span class="input-group-text" id="basic-addon2">GB</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.storageSize) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Clients</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfClients)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfClients, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfClients) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Employees</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfEmployee)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfEmployee, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfEmployee) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Users</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 ">
                  <div class="input-group mb-3 {% if form_errors(form.CAEmployeeAndOwnerLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.CAEmployeeAndOwnerLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">CA Employee & OwnerLogin</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.CAEmployeeAndOwnerLogin) }}
                  </div>
                  <div class="input-group mb-3 {% if form_errors(form.ClientOwnerAndEmployeeLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.ClientOwnerAndEmployeeLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">ClientOwner & Employee Login</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.ClientOwnerAndEmployeeLogin) }}
                  </div>
                  <div class="input-group mb-3 {% if form_errors(form.ClientVendorLogin)|length > 0 %} div-form-error{% endif %}">
                    {{ form_widget(form.ClientVendorLogin, {'attr': {'class': 'form-control','min':'1','aria-describedby':'basic-addon2'}}) }}
                    <span class="input-group-text" id="basic-addon2">Client Vendor Login</span>
                  </div>
                  <div class="form-error">
                    {{ form_errors(form.ClientVendorLogin) }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">No Of Transactions</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.noOfTransaction)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.noOfTransaction, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.noOfTransaction) }}
                 </div>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Features</label>
                </div>
                <div class="col">
                  <div class="py-2 mb-2">
                    <div class="row">
                      <div class="col-12">
                        <div class="form-check form-switch mb-0">                          
                          {{ form_widget(form.taskManager, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_1">Task Manager</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.fileManager, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_2">File Manager</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.eCommerce, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_4">E-Commerce</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.templateCustomization, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_5">Tamplate - Customization for import</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.liveReportClientMobileApp, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_6">Live reports on client mobile app</label>
                        </div>
                        <div class="form-check form-switch mb-0">
                          {{ form_widget(form.clientLoginApp, {'attr': {'class': 'form-check-input'}}) }}
                          <label class="form-check-label" for="fe_chk_6">Client Login Mobile App</label>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Price</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4 {% if form_errors(form.price)|length > 0 %} div-form-error{% endif %}">
                  {{ form_widget(form.price, {'attr': {'class': 'form-control mb-3','min':'1'}}) }}
                  <div class="form-error">
                    {{ form_errors(form.price) }}
                 </div>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Status</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                  {{ form_widget(form.status, {'attr': {'class': 'form-select form-select-sm mb-3'}}) }}
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <label class="form-label" style="min-width:180px;" for="">Display on Portal</label>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                  <div class="form-check form-switch">
                    {{ form_widget(form.displayOnPortal, {'attr': {'class': 'form-check-input'}}) }}
                    <label class="form-check-label" for="dp_radio_7">Yes</label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12 my-2 text-end">
                  <button type="submit" class="btn btn-primary">Edit Plan</button>
                </div>
              </div>
            {{ form_end(form) }}

          </div>
        </div>
{% endblock %}